image: openjdk:17-slim

pages:
  stage: deploy
  script:
    - echo "Copying results to /public for publishing..."
    - rm -rf public/
    - mkdir public
    - cp -r docs/* public/
  artifacts:
    paths:
      - public
  #rules:
  #  - if: $CI_COMMIT_TAG
